name: bloc_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: null
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: null
  freezed_annotation: null
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: null

flutter:
  uses-material-design: true
